---
deployment:
  tasks:
    - export DEPLOYPATH=/home/diflniqt/public_html/wp-content/plugins/genesis-wp-members
    - test -d "$(dirname $DEPLOYPATH)" || exit 1
    - mkdir -p $DEPLOYPATH
    - /bin/cp URM-members.php $DEPLOYPATH/
    - /bin/cp dc-link-my-page.php $DEPLOYPATH/
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
